export const METADATA_KEYS = {
	METHOD: "restify:method",
	COLLECTION: "restify:collection",
	PARAMETERS: "restify:parameters",
	LOGGER: "restify:logger",
	ON_ERROR: "restify:onError",
	TRANSFORM: "restify:transform",
	DEPRECATED: "restify:deprecated",
	RESPONSE_TYPE: "restify:responseType",
	BASE_URL: "restify:baseUrl",
	FORM_URL_ENCODED: "restify:formUrlEncoded",
	WITH_CREDENTIALS: "restify:withCredentials",
	BEFORE_REQUEST: "restify:beforeRequest",
	AFTER_RESPONSE: "restify:afterResponse",
	RETRY: "restify:retry",
	CANCELABLE: "restify:cancelable",
	MOCK: "restify:mock",
} as const;
