import { readdir, stat, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { consola } from "consola";

interface RouteInfo {
	path: string;
	filePath: string;
	params: string[];
}

/**
 * Convert file path to route path
 * Examples:
 *   users.ts → /users
 *   posts.ts → /posts
 *   todo-items.ts → /todo-items
 */
function filePathToRoute(filePath: string): RouteInfo {
	// Remove .ts extension
	const withoutExt = filePath.replace(/\.ts$/, "");

	// Simple path conversion - no dynamic params
	const routePath = `/${withoutExt}`;

	return {
		path: routePath,
		filePath,
		params: [], // No params in simplified version
	};
}

/**
 * Recursively scan directory for .ts files
 */
async function scanDirectory(
	dir: string,
	baseDir: string,
): Promise<RouteInfo[]> {
	const routes: RouteInfo[] = [];

	try {
		const entries = await readdir(dir);

		for (const entry of entries) {
			const fullPath = join(dir, entry);
			const stats = await stat(fullPath);

			if (stats.isDirectory()) {
				// Recursively scan subdirectories
				const subRoutes = await scanDirectory(fullPath, baseDir);
				routes.push(...subRoutes);
			} else if (
				entry.endsWith(".ts") &&
				!entry.endsWith(".gen.ts") &&
				!entry.includes("$")
			) {
				// Convert file path to route
				const relativePath = relative(baseDir, fullPath);
				const routeInfo = filePathToRoute(relativePath);
				routes.push(routeInfo);
			}
		}
	} catch (error) {
		if ((error as { code?: string }).code !== "ENOENT") {
			throw error;
		}
		consola.warn(`Directory ${dir} does not exist`);
	}

	return routes;
}

/**
 * Generate TypeScript code for routes
 */
function generateRoutesCode(routes: RouteInfo[]): string {
	const imports = routes
		.map(
			(route, index) =>
				`import * as Route${index} from './api/${route.filePath}';`,
		)
		.join("\n");
	const routeEntries = routes
		.map(
			(route, index) =>
				`  '${route.path}': { module: Route${index}, params: ${JSON.stringify(route.params)} }`,
		)
		.join(",\n");

	// Generate type for route paths
	const routePaths = routes.map((route) => `  | '${route.path}'`).join("\n");

	// Generate type for route params
	const routeParamsTypes = routes
		.filter((route) => route.params.length > 0)
		.map((route) => {
			const paramsType = `{ ${route.params.map((p) => `${p}: string`).join(", ")} }`;
			return `  '${route.path}': ${paramsType};`;
		})
		.join("\n");

	const code = `/**
 * 🚀 Auto-generated by restify-gen
 * Do not edit manually
 */

${imports}

export const apiRoutes = {
${routeEntries}
} as const;

export type ApiRoutes = typeof apiRoutes;

export type RoutePath =
${routePaths || "  never"};

export type RouteParams = {
${routeParamsTypes || "  // No routes with params"}
};

export type RouteParamsFor<T extends RoutePath> = T extends keyof RouteParams
  ? RouteParams[T]
  : Record<string, never>;
`;

	return code;
}

/**
 * Main generator function
 */
export async function generateRoutes(
	apiDir: string,
	outputFile: string,
): Promise<void> {
	consola.info(`📂 Scanning ${apiDir}...`);

	const routes = await scanDirectory(apiDir, apiDir);

	consola.info(`📋 Found ${routes.length} route(s)`);

	for (const route of routes) {
		consola.info(`  ${route.path} → ${route.filePath}`);
	}

	const code = generateRoutesCode(routes);

	await writeFile(outputFile, code, "utf-8");

	consola.success(`✓ Generated ${outputFile}`);
}
